// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestProtocStruMsg.proto

#ifndef PROTOBUF_TestProtocStruMsg_2eproto__INCLUDED
#define PROTOBUF_TestProtocStruMsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_TestProtocStruMsg_2eproto();
void protobuf_AssignDesc_TestProtocStruMsg_2eproto();
void protobuf_ShutdownFile_TestProtocStruMsg_2eproto();

class TestProtocStru;

// ===================================================================

class TestProtocStru : public ::google::protobuf::Message {
 public:
  TestProtocStru();
  virtual ~TestProtocStru();

  TestProtocStru(const TestProtocStru& from);

  inline TestProtocStru& operator=(const TestProtocStru& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestProtocStru& default_instance();

  void Swap(TestProtocStru* other);

  // implements Message ----------------------------------------------

  TestProtocStru* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TestProtocStru& from);
  void MergeFrom(const TestProtocStru& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string value1 = 1;
  inline bool has_value1() const;
  inline void clear_value1();
  static const int kValue1FieldNumber = 1;
  inline const ::std::string& value1() const;
  inline void set_value1(const ::std::string& value);
  inline void set_value1(const char* value);
  inline void set_value1(const char* value, size_t size);
  inline ::std::string* mutable_value1();
  inline ::std::string* release_value1();
  inline void set_allocated_value1(::std::string* value1);

  // required int32 value2 = 2;
  inline bool has_value2() const;
  inline void clear_value2();
  static const int kValue2FieldNumber = 2;
  inline ::google::protobuf::int32 value2() const;
  inline void set_value2(::google::protobuf::int32 value);

  // required bool value3 = 3;
  inline bool has_value3() const;
  inline void clear_value3();
  static const int kValue3FieldNumber = 3;
  inline bool value3() const;
  inline void set_value3(bool value);

  // @@protoc_insertion_point(class_scope:TestProtocStru)
 private:
  inline void set_has_value1();
  inline void clear_has_value1();
  inline void set_has_value2();
  inline void clear_has_value2();
  inline void set_has_value3();
  inline void clear_has_value3();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* value1_;
  ::google::protobuf::int32 value2_;
  bool value3_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_TestProtocStruMsg_2eproto();
  friend void protobuf_AssignDesc_TestProtocStruMsg_2eproto();
  friend void protobuf_ShutdownFile_TestProtocStruMsg_2eproto();

  void InitAsDefaultInstance();
  static TestProtocStru* default_instance_;
};
// ===================================================================


// ===================================================================

// TestProtocStru

// required string value1 = 1;
inline bool TestProtocStru::has_value1() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TestProtocStru::set_has_value1() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TestProtocStru::clear_has_value1() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TestProtocStru::clear_value1() {
  if (value1_ != &::google::protobuf::internal::kEmptyString) {
    value1_->clear();
  }
  clear_has_value1();
}
inline const ::std::string& TestProtocStru::value1() const {
  return *value1_;
}
inline void TestProtocStru::set_value1(const ::std::string& value) {
  set_has_value1();
  if (value1_ == &::google::protobuf::internal::kEmptyString) {
    value1_ = new ::std::string;
  }
  value1_->assign(value);
}
inline void TestProtocStru::set_value1(const char* value) {
  set_has_value1();
  if (value1_ == &::google::protobuf::internal::kEmptyString) {
    value1_ = new ::std::string;
  }
  value1_->assign(value);
}
inline void TestProtocStru::set_value1(const char* value, size_t size) {
  set_has_value1();
  if (value1_ == &::google::protobuf::internal::kEmptyString) {
    value1_ = new ::std::string;
  }
  value1_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TestProtocStru::mutable_value1() {
  set_has_value1();
  if (value1_ == &::google::protobuf::internal::kEmptyString) {
    value1_ = new ::std::string;
  }
  return value1_;
}
inline ::std::string* TestProtocStru::release_value1() {
  clear_has_value1();
  if (value1_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = value1_;
    value1_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TestProtocStru::set_allocated_value1(::std::string* value1) {
  if (value1_ != &::google::protobuf::internal::kEmptyString) {
    delete value1_;
  }
  if (value1) {
    set_has_value1();
    value1_ = value1;
  } else {
    clear_has_value1();
    value1_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required int32 value2 = 2;
inline bool TestProtocStru::has_value2() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TestProtocStru::set_has_value2() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TestProtocStru::clear_has_value2() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TestProtocStru::clear_value2() {
  value2_ = 0;
  clear_has_value2();
}
inline ::google::protobuf::int32 TestProtocStru::value2() const {
  return value2_;
}
inline void TestProtocStru::set_value2(::google::protobuf::int32 value) {
  set_has_value2();
  value2_ = value;
}

// required bool value3 = 3;
inline bool TestProtocStru::has_value3() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TestProtocStru::set_has_value3() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TestProtocStru::clear_has_value3() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TestProtocStru::clear_value3() {
  value3_ = false;
  clear_has_value3();
}
inline bool TestProtocStru::value3() const {
  return value3_;
}
inline void TestProtocStru::set_value3(bool value) {
  set_has_value3();
  value3_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_TestProtocStruMsg_2eproto__INCLUDED
