// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestProtocStruMsg.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "TestProtocStruMsg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* TestProtocStru_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TestProtocStru_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_TestProtocStruMsg_2eproto() {
  protobuf_AddDesc_TestProtocStruMsg_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "TestProtocStruMsg.proto");
  GOOGLE_CHECK(file != NULL);
  TestProtocStru_descriptor_ = file->message_type(0);
  static const int TestProtocStru_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestProtocStru, value1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestProtocStru, value2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestProtocStru, value3_),
  };
  TestProtocStru_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TestProtocStru_descriptor_,
      TestProtocStru::default_instance_,
      TestProtocStru_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestProtocStru, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestProtocStru, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TestProtocStru));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_TestProtocStruMsg_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TestProtocStru_descriptor_, &TestProtocStru::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_TestProtocStruMsg_2eproto() {
  delete TestProtocStru::default_instance_;
  delete TestProtocStru_reflection_;
}

void protobuf_AddDesc_TestProtocStruMsg_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\027TestProtocStruMsg.proto\"@\n\016TestProtocS"
    "tru\022\016\n\006value1\030\001 \002(\t\022\016\n\006value2\030\002 \002(\005\022\016\n\006v"
    "alue3\030\003 \002(\010", 91);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "TestProtocStruMsg.proto", &protobuf_RegisterTypes);
  TestProtocStru::default_instance_ = new TestProtocStru();
  TestProtocStru::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_TestProtocStruMsg_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_TestProtocStruMsg_2eproto {
  StaticDescriptorInitializer_TestProtocStruMsg_2eproto() {
    protobuf_AddDesc_TestProtocStruMsg_2eproto();
  }
} static_descriptor_initializer_TestProtocStruMsg_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int TestProtocStru::kValue1FieldNumber;
const int TestProtocStru::kValue2FieldNumber;
const int TestProtocStru::kValue3FieldNumber;
#endif  // !_MSC_VER

TestProtocStru::TestProtocStru()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void TestProtocStru::InitAsDefaultInstance() {
}

TestProtocStru::TestProtocStru(const TestProtocStru& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void TestProtocStru::SharedCtor() {
  _cached_size_ = 0;
  value1_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  value2_ = 0;
  value3_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TestProtocStru::~TestProtocStru() {
  SharedDtor();
}

void TestProtocStru::SharedDtor() {
  if (value1_ != &::google::protobuf::internal::kEmptyString) {
    delete value1_;
  }
  if (this != default_instance_) {
  }
}

void TestProtocStru::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TestProtocStru::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TestProtocStru_descriptor_;
}

const TestProtocStru& TestProtocStru::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_TestProtocStruMsg_2eproto();
  return *default_instance_;
}

TestProtocStru* TestProtocStru::default_instance_ = NULL;

TestProtocStru* TestProtocStru::New() const {
  return new TestProtocStru;
}

void TestProtocStru::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_value1()) {
      if (value1_ != &::google::protobuf::internal::kEmptyString) {
        value1_->clear();
      }
    }
    value2_ = 0;
    value3_ = false;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TestProtocStru::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string value1 = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value1()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->value1().data(), this->value1().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_value2;
        break;
      }

      // required int32 value2 = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_value2:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &value2_)));
          set_has_value2();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_value3;
        break;
      }

      // required bool value3 = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_value3:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &value3_)));
          set_has_value3();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void TestProtocStru::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string value1 = 1;
  if (has_value1()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->value1().data(), this->value1().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->value1(), output);
  }

  // required int32 value2 = 2;
  if (has_value2()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->value2(), output);
  }

  // required bool value3 = 3;
  if (has_value3()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->value3(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* TestProtocStru::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string value1 = 1;
  if (has_value1()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->value1().data(), this->value1().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->value1(), target);
  }

  // required int32 value2 = 2;
  if (has_value2()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->value2(), target);
  }

  // required bool value3 = 3;
  if (has_value3()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->value3(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int TestProtocStru::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string value1 = 1;
    if (has_value1()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->value1());
    }

    // required int32 value2 = 2;
    if (has_value2()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->value2());
    }

    // required bool value3 = 3;
    if (has_value3()) {
      total_size += 1 + 1;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TestProtocStru::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TestProtocStru* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TestProtocStru*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TestProtocStru::MergeFrom(const TestProtocStru& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_value1()) {
      set_value1(from.value1());
    }
    if (from.has_value2()) {
      set_value2(from.value2());
    }
    if (from.has_value3()) {
      set_value3(from.value3());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TestProtocStru::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TestProtocStru::CopyFrom(const TestProtocStru& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestProtocStru::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void TestProtocStru::Swap(TestProtocStru* other) {
  if (other != this) {
    std::swap(value1_, other->value1_);
    std::swap(value2_, other->value2_);
    std::swap(value3_, other->value3_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TestProtocStru::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TestProtocStru_descriptor_;
  metadata.reflection = TestProtocStru_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
